interactions:
- request:
    body: !!python/unicode '{"searchAreaWkt": "POLYGON ((-105.0207996368408345 39.7338828628182839,
      -105.0207996368408345 39.7365972921260067, -105.0158751010894775 39.7365972921260067,
      -105.0158751010894775 39.7338828628182839, -105.0207996368408345 39.7338828628182839))",
      "types": ["IDAHOImage"], "filters": ["catalogID = ''10400100203F1300''"]}'
    headers:
      Accept: ['*/*']
      Accept-Encoding: ['gzip, deflate']
      Connection: [keep-alive]
      Content-Length: ['318']
      User-Agent: [python-requests/2.14.2]
    method: POST
    uri: https://geobigdata.io/catalog/v2/search
  response:
    body: {string: !!python/unicode "\n{\n  \"status\": \"401 Unauthorized\",\n  \"message\"
        : \"Authentication Failed.\"\n}\n"}
    headers:
      access-control-allow-origin: ['*']
      connection: [keep-alive]
      content-length: ['76']
      content-type: [application/json]
      date: ['Thu, 06 Jul 2017 22:26:12 GMT']
      via: [kong/0.5.2]
      x-amz-cf-id: [xETXewfIJIIOnufOV10N0yLkuD4OAD7RgVuOYXq7eRuwMP3Zic0DZg==]
      x-amzn-requestid: [1d9c2f78-629a-11e7-9c07-f3d6ecfdff6d]
      x-amzn-trace-id: [sampled=0;root=1-595eb903-162ac2e55418cd6f5c96792d]
      x-cache: [Error from cloudfront]
    status: {code: 401, message: Unauthorized}
version: 1
