interactions:
- request:
    body: null
    headers:
      Accept: ['*/*']
      Accept-Encoding: ['gzip, deflate']
      Connection: [keep-alive]
      User-Agent: [python-requests/2.14.2]
    method: GET
    uri: https://geobigdata.io/catalog/v2/record/10400100203F1300?includeRelationships=false
  response:
    body: {string: !!python/unicode "\n{\n  \"status\": \"401 Unauthorized\",\n  \"message\"
        : \"Authentication Failed.\"\n}\n"}
    headers:
      access-control-allow-origin: ['*']
      connection: [keep-alive]
      content-length: ['76']
      content-type: [application/json]
      date: ['Thu, 06 Jul 2017 22:26:11 GMT']
      via: [kong/0.5.2]
      x-amz-cf-id: [5PF7Je3aEUpfwabE9jET6mTSnbCP9FHyGqXiAfWL2fFdoG78aQC2GQ==]
      x-amzn-requestid: [1d4dc12e-629a-11e7-bc07-b38a9711b926]
      x-amzn-trace-id: [sampled=0;root=1-595eb903-bc4e23d86d81e1b63b716737]
      x-cache: [Error from cloudfront]
    status: {code: 401, message: Unauthorized}
version: 1
